s3:
  bucket: "data-lake-ms"

sources:
  - name: "postgres_source"
    url: "jdbc:postgresql://poc-postgres.cnkoswoqk901.eu-north-1.rds.amazonaws.com:5432/transactional_db"
    driver: "org.postgresql.Driver"
    user: "dbadmin"
    password: "${DB_PASS_POSTGRES}"
    tables:
      - name: "production.vendors"
        pii_columns: ["name"]

  - name: "mysql_source"
    url: "jdbc:mysql://poc-mysql.cnkoswoqk901.eu-north-1.rds.amazonaws.com:3306/source_db?allowPublicKeyRetrieval=true&useSSL=false"
    driver: "com.mysql.cj.jdbc.Driver"
    user: "admin"
    password: "${DB_PASS_MYSQL}"
    tables:
      - name: "vendors"
        pii_columns: ["name"]